In [1]:
print("hello")

hello


In [2]:
#pip install torch numpy --quiet

In [3]:
import torch

normal tensor

In [4]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [5]:
t1.dtype

torch.float32

vector using tensor

In [6]:
t2=torch.tensor([1,2,3,4])
t2

tensor([1, 2, 3, 4])

In [7]:
t2.dtype

torch.int64

take one float value, for this reason all will be float

In [8]:
t2=torch.tensor([1,2,3.,4])
t2

tensor([1., 2., 3., 4.])

In [9]:
t2.dtype

torch.float32

matrix

In [10]:
t3=torch.tensor([[1,2,3],
                 [4,5,6]])
t3

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
t3.dtype

torch.int64

In [12]:
t3.ndim

2

similarly we can create k-dimesional matrix

how many rows and columns

In [13]:
print(t1.shape)
print(t2.shape)
print(t3.shape)

torch.Size([])
torch.Size([4])
torch.Size([2, 3])


must need tensor shape proper, without proper shape tensor will not create

### Tensor Operations

In [14]:
x= torch.tensor(3.)
w=torch.tensor(4., requires_grad=True)
b=torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [15]:
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [16]:
y.backward()

In [17]:
y

tensor(17., grad_fn=<AddBackward0>)

In [18]:
print(x)
print(w)
print(b)

tensor(3.)
tensor(4., requires_grad=True)
tensor(5., requires_grad=True)


In [19]:
print("dy/dw = x", w.grad)
print("dy/dx = w", x.grad)
print("dy/db = 1", b.grad)

dy/dw = x tensor(3.)
dy/dx = w None
dy/db = 1 tensor(1.)


here `x.grad = none`, beacause we did not declare `x` as `requires_grad=true`

### numpy with pytorch

In [20]:
import numpy as np

In [24]:
x = np.array([[1,2,3,4],[5,6,7,8.]])
x

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

convert into tensor

In [25]:
y = torch.from_numpy(x)
y

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], dtype=torch.float64)

In [26]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

convert into numpy array

In [27]:
z = y.numpy()
z

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [28]:
x.dtype, y.dtype, z.dtype

(dtype('float64'), torch.float64, dtype('float64'))