# PyTorch Tensor Creation Functions

## A. Tensor Creation (Basic Level)

These functions are used to create tensors in PyTorch.

| Function           | Purpose                                                                  |
| ------------------ | ------------------------------------------------------------------------ |
| `torch.tensor()`   | Converts normal data into a tensor                                       |
| `torch.zeros()`    | Creates a tensor filled with zeros                                       |
| `torch.ones()`     | Creates a tensor filled with ones                                        |
| `torch.empty()`    | Allocates memory without initialization (contains random/garbage values) |
| `torch.rand()`     | Creates random values between `0–1`                                      |
| `torch.randn()`    | Creates random values from a normal distribution                         |
| `torch.randint()`  | Creates random integer values                                            |
| `torch.arange()`   | Creates a range of values                                                |
| `torch.linspace()` | Creates equally spaced values                                            |
| `torch.eye()`      | Creates an identity matrix                                               |

---

# Quick Examples

## 1. `torch.tensor()`

```python
import torch

x = torch.tensor([1, 2, 3])

print(x)
```

---

## 2. `torch.zeros()`

```python
x = torch.zeros((3, 4))

print(x)
```

---

## 3. `torch.ones()`

```python
x = torch.ones((2, 3))

print(x)
```

---

## 4. `torch.empty()`

```python
x = torch.empty((2, 2))

print(x)
```

---

## 5. `torch.rand()`

```python
x = torch.rand((2, 3))

print(x)
```

---

## 6. `torch.randn()`

```python
x = torch.randn((2, 3))

print(x)
```

---

## 7. `torch.randint()`

```python
x = torch.randint(0, 10, (3, 4))

print(x)
```

---

## 8. `torch.arange()`

```python
x = torch.arange(0, 10)

print(x)
```

---

## 9. `torch.linspace()`

```python
x = torch.linspace(0, 10, 5)

print(x)
```

---

## 10. `torch.eye()`

```python
x = torch.eye(4)

print(x)
```

---

# Key Differences

## `torch.rand()` vs `torch.randn()`

| Function        | Output Type                                                    |
| --------------- | -------------------------------------------------------------- |
| `torch.rand()`  | Random values between `0–1`                                    |
| `torch.randn()` | Random values from a normal distribution (positive + negative) |

---

## `torch.arange()` vs `torch.linspace()`

| Function           | Purpose                                         |
| ------------------ | ----------------------------------------------- |
| `torch.arange()`   | Creates values with a fixed step size           |
| `torch.linspace()` | Creates a fixed number of equally spaced values |

---

# Beginner Notes

* `torch.tensor()` → Convert your own data into a tensor
* `torch.zeros()` → Initialize tensors with zeros
* `torch.ones()` → Use for masks or default values
* `torch.empty()` → Avoid as a beginner (contains uninitialized values)
* `torch.rand()` → Generate random values between `0–1`
* `torch.randn()` → Commonly used for weight initialization
* `torch.randint()` → Generate random integer labels
* `torch.arange()` → Create ranges of numbers
* `torch.linspace()` → Create equally spaced values
* `torch.eye()` → Create identity matrices


### torch.tensor()

In [1]:
import torch

In [2]:
x0 = torch.tensor(5.)
x0

tensor(5.)

In [3]:
x1 = torch.tensor([1,2,3.,4])
x1

tensor([1., 2., 3., 4.])

In [4]:
x2 = torch.tensor([[1,2,3],[4,5.,6]])
x2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [5]:
x3 = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
x3

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

we can create n-dimentional tensor using tensor function

### torch.zeros()

create n-dimensional 0 values all

In [6]:
z1 = torch.zeros(8)
z1

tensor([0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
z2 = torch.zeros((3,4))
z2

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

if we need zeros vector or matrix,, by default its values will float

In [8]:
z_int = torch.zeros((3,4,5), dtype=int)
z_int

tensor([[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]])

### torch.ones()

create n-dimensional all values 1

In [9]:
one = torch.ones(5)
one

tensor([1., 1., 1., 1., 1.])

In [10]:
one_int = torch.ones((3,4), dtype=int)
one_int

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

### torch.empty()

create n-dimesional matrix/vector with empty values <br>
here can be garbage value

memory allocated but do not value intialized

In [11]:
empty_tensor = torch.empty((3,4))
empty_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### torch.rand()

create n-dimensional random value between 0 to 1

here parameter value means `how many values you want to generate`, `it does not mean that torch.rand(100) means 0-100`

In [12]:
rand_021 = torch.rand((3,4))
rand_021

tensor([[0.5830, 0.2233, 0.4490, 0.5912],
        [0.0129, 0.9421, 0.5581, 0.9738],
        [0.7400, 0.2342, 0.7471, 0.1760]])

### torch.randn()

it follows normal distribution, and it can be positive/negative

here all values `mean=0` and `standard deviation=1`

In [13]:
randn = torch.randn((3,2))
randn

tensor([[ 1.6751,  0.5281],
        [ 1.3209,  0.3123],
        [-0.0458,  0.7543]])

### torch.randint()

torch.randint(
    low,
    high,
    shape
)

generate random integer values

In [14]:
randomint = torch.randint(2,99,(3,4))
randomint

tensor([[36, 74, 67, 45],
        [52, 89, 88, 22],
        [73, 23, 33, 93]])

### torch.arange()

range create a range value,, `0 to value-1`

In [15]:
rangeValue= torch.arange(19)
rangeValue

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18])

it can be `start-end`

In [16]:
rangeValue = torch.arange(3,9)
rangeValue

tensor([3, 4, 5, 6, 7, 8])

### torch.linspace()

it make `equal-interval-number`

torch.linspace(
    start,
    end,
    steps
)

here steps means `how many values we need after interval`

In [17]:
interval_number = torch.linspace(1,19,9)
interval_number

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000, 12.2500, 14.5000, 16.7500,
        19.0000])

### torch.eye()

it creates `identity matrix`, that means column 1, and other all values 0

In [18]:
indentity_matrix=torch.eye(5)
indentity_matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])