# PyTorch Tensor Manipulation Functions

## C. Tensor Manipulation (Basic Level)

These functions are used to **modify tensor shape, dimensions, and structure**.

They help answer questions like:

* How to change tensor shape?
* How to flatten data?
* How to add or remove dimensions?
* How to rearrange dimensions?

---

# 1. `.reshape()`

Changes the shape of a tensor.

### Example

```python
import torch

x = torch.arange(12)

x = x.reshape(3, 4)

print(x)
```

### Output

```python
tensor([
 [0, 1, 2, 3],
 [4, 5, 6, 7],
 [8, 9, 10, 11]
])
```

---

# 2. `.view()`

Similar to `.reshape()`.

Used to change tensor shape.

### Example

```python
x = torch.arange(12)

x = x.view(2, 6)

print(x)
```

---

# 3. `.flatten()`

Converts a multi-dimensional tensor into a 1D tensor.

### Example

```python
x = torch.tensor([
    [1, 2],
    [3, 4]
])

print(x.flatten())
```

### Output

```python
tensor([1, 2, 3, 4])
```

---

# 4. `.squeeze()`

Removes dimensions of size `1`.

### Example

```python
x = torch.rand((1, 3, 1))

print(x.shape)

x = x.squeeze()

print(x.shape)
```

### Output

```python
torch.Size([1, 3, 1])

torch.Size([3])
```

---

# 5. `.unsqueeze()`

Adds a new dimension.

### Example

```python
x = torch.tensor([1, 2, 3])

x = x.unsqueeze(0)

print(x.shape)
```

### Output

```python
torch.Size([1, 3])
```

---

# 6. `.permute()`

Rearranges tensor dimensions.

### Example

```python
x = torch.rand((224, 224, 3))

x = x.permute(2, 0, 1)

print(x.shape)
```

### Output

```python
torch.Size([3, 224, 224])
```

---

# 7. `.transpose()`

Swaps two dimensions.

### Example

```python
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

x = x.transpose(0, 1)

print(x)
```

### Output

```python
tensor([
 [1, 4],
 [2, 5],
 [3, 6]
])
```

---

# Quick Summary Table

| Function       | Purpose                      |
| -------------- | ---------------------------- |
| `.reshape()`   | Changes tensor shape         |
| `.view()`      | Reshapes tensor              |
| `.flatten()`   | Converts to 1D tensor        |
| `.squeeze()`   | Removes dimensions of size 1 |
| `.unsqueeze()` | Adds a dimension             |
| `.permute()`   | Rearranges dimensions        |
| `.transpose()` | Swaps dimensions             |

---

# Practice

Try this:

```python
x = torch.rand((2, 3, 4))
```

Then test:

```python
x.reshape(6, 4)
x.flatten()
x.squeeze()
x.unsqueeze(0)
x.permute(2, 0, 1)
```


### .reshape()

In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
x.shape

torch.Size([3, 4])

In [6]:
x = x.reshape(4,3)
x

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [7]:
x.shape

torch.Size([4, 3])

In [8]:
x= x.reshape(2,6)
x

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [9]:
x.shape

torch.Size([2, 6])

In [10]:
x = x.reshape(6,2)
x

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [11]:
x.shape

torch.Size([6, 2])

In [12]:
x = x.reshape(5,2)
x

RuntimeError: shape '[5, 2]' is invalid for input of size 12

In [13]:
x=x.reshape(4,-1)
x

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

`-1` is special number, that calculate another number of dimension autometically

In [14]:
x= x.reshape(-1)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### .view()

it is same as .reshape <br>
but .reshape is safer and can handle memory issue

In [15]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
x = x.view(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### .flatten()

multi dimension tensor to 1D tensor

In [17]:
x = torch.randn(1,2,3)
x

tensor([[[-1.1181, -0.3560,  0.5540],
         [ 0.7214,  0.6634, -1.1127]]])

In [18]:
x=x.flatten()
x

tensor([-1.1181, -0.3560,  0.5540,  0.7214,  0.6634, -1.1127])

### .squeeze()

remove -> which dimesion size = 1

In [19]:
x = torch.rand((1,3,1))

print(x.shape)

torch.Size([1, 3, 1])


In [20]:
x=x.squeeze()
x.shape

torch.Size([3])

### .unsqueeze()

new dimension add

In [30]:
x = torch.tensor([1,2,3])
x.shape

torch.Size([3])

In [31]:
x

tensor([1, 2, 3])

In [32]:
x=x.unsqueeze(0)
x.shape

torch.Size([1, 3])

In [33]:
x

tensor([[1, 2, 3]])

In [34]:
x=x.unsqueeze(1)
x.shape

torch.Size([1, 1, 3])

In [35]:
x

tensor([[[1, 2, 3]]])

In [36]:
x=x.unsqueeze(2)
x.shape

torch.Size([1, 1, 1, 3])

In [37]:
x

tensor([[[[1, 2, 3]]]])

### .permute()

Tensor dimension rearrange <br>
that means ` change dimension order`

In [42]:
x=torch.rand((4,4,3)) # images -> hight, width, channel
x

tensor([[[0.4106, 0.3113, 0.8771],
         [0.7391, 0.7825, 0.0805],
         [0.9834, 0.8172, 0.3266],
         [0.2644, 0.4697, 0.7707]],

        [[0.1649, 0.8775, 0.3537],
         [0.1309, 0.4220, 0.2514],
         [0.1560, 0.1297, 0.5417],
         [0.3306, 0.6355, 0.9221]],

        [[0.9514, 0.4831, 0.3208],
         [0.4278, 0.0052, 0.3371],
         [0.9148, 0.8725, 0.1185],
         [0.5824, 0.5261, 0.8238]],

        [[0.7661, 0.9125, 0.1856],
         [0.5751, 0.9635, 0.9475],
         [0.7005, 0.1818, 0.5124],
         [0.5859, 0.7382, 0.1127]]])

In [44]:
x=x.permute(2,0,1) # 2-> 3rd, 1->2nd, 0->1st
x

tensor([[[0.4106, 0.1649, 0.9514, 0.7661],
         [0.3113, 0.8775, 0.4831, 0.9125],
         [0.8771, 0.3537, 0.3208, 0.1856]],

        [[0.7391, 0.1309, 0.4278, 0.5751],
         [0.7825, 0.4220, 0.0052, 0.9635],
         [0.0805, 0.2514, 0.3371, 0.9475]],

        [[0.9834, 0.1560, 0.9148, 0.7005],
         [0.8172, 0.1297, 0.8725, 0.1818],
         [0.3266, 0.5417, 0.1185, 0.5124]],

        [[0.2644, 0.3306, 0.5824, 0.5859],
         [0.4697, 0.6355, 0.5261, 0.7382],
         [0.7707, 0.9221, 0.8238, 0.1127]]])

### .transpose()

2 pis dimension swap

In [45]:
x = torch.tensor([
 [1,2,3],
 [4,5,6]
])

print(x.shape)

torch.Size([2, 3])


In [46]:
x = x.transpose(0,1)

print(x)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
