# PyTorch Tensor Information Functions

## B. Tensor Information (Basic Level)

These functions are used to get information about a tensor.

They help answer questions like:

* What is the tensor shape?
* How many dimensions does it have?
* What is the data type?
* Is it on CPU or GPU?
* How many total elements exist?

---

# 1. `.shape`

Returns the **shape (structure)** of a tensor.

### Example

```python id="mh3m9v"
import torch

x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(x.shape)
```

### Output

```python id="luij7r"
torch.Size([2, 3])
```

Meaning:

* 2 rows
* 3 columns

---

# 2. `.size()`

Returns the **size of the tensor**.

It works similarly to `.shape`.

### Example

```python id="jlwm8f"
x = torch.rand((2, 4))

print(x.size())
```

### Output

```python id="18t6gh"
torch.Size([2, 4])
```

---

### Get Specific Dimension Size

```python id="w31t7r"
print(x.size(0))
```

Output:

```python id="kz6bgz"
2
```

```python id="z09d6o"
print(x.size(1))
```

Output:

```python id="s74y10"
4
```

---

# 3. `.dtype`

Returns the **data type** of a tensor.

### Example

```python id="2zvucq"
x = torch.tensor([1, 2, 3])

print(x.dtype)
```

### Output

```python id="if1gcf"
torch.int64
```

---

### Float Example

```python id="m8oowu"
x = torch.tensor([1.0, 2.0])

print(x.dtype)
```

### Output

```python id="s4vhuk"
torch.float32
```

---

### Common Data Types

| Type            | Meaning                |
| --------------- | ---------------------- |
| `torch.int32`   | Integer                |
| `torch.int64`   | Large Integer          |
| `torch.float32` | Float                  |
| `torch.float64` | Double Precision Float |
| `torch.bool`    | True / False           |

---

### Type Conversion

```python id="cknpju"
x = x.float()
```

```python id="jlwmjl"
x = x.int()
```

---

# 4. `.device`

Returns the **device location** of a tensor.

It tells whether the tensor is stored on:

* CPU
* GPU

### Example

```python id="st7kz0"
x = torch.tensor([1, 2, 3])

print(x.device)
```

### Output

```python id="2ksjlwm"
cpu
```

---

### GPU Example

```python id="1sllgw"
device = torch.device("cuda")

x = x.to(device)

print(x.device)
```

### Output

```python id="s7flsh"
cuda:0
```

---

# 5. `.ndim`

Returns the **number of dimensions** of a tensor.

### Example 1 — Scalar

```python id="zr5t5f"
x = torch.tensor(5)

print(x.ndim)
```

Output:

```python id="k7ojxk"
0
```

---

### Example 2 — Vector

```python id="br7v1h"
x = torch.tensor([1, 2, 3])

print(x.ndim)
```

Output:

```python id="lttowg"
1
```

---

### Example 3 — Matrix

```python id="vjqkj6"
x = torch.tensor([
    [1, 2],
    [3, 4]
])

print(x.ndim)
```

Output:

```python id="mnf9kc"
2
```

---

### Dimension Reference Table

| Tensor Type     | Dimension |
| --------------- | --------- |
| Scalar          | 0D        |
| Vector          | 1D        |
| Matrix          | 2D        |
| Image           | 3D        |
| Batch of Images | 4D        |

---

# 6. `.numel()`

Returns the **total number of elements** in a tensor.

### Example

```python id="c4g0g2"
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(x.numel())
```

### Output

```python id="psuzxr"
6
```

Because:

```python id="dppnm9"
2 × 3 = 6
```

---

### Another Example

```python id="75j5kp"
x = torch.rand((4, 5, 2))

print(x.numel())
```

### Output

```python id="udl6k0"
40
```

Because:

```python id="fz6t6v"
4 × 5 × 2 = 40
```

---

# Quick Summary Table

| Function   | Purpose                          |
| ---------- | -------------------------------- |
| `.shape`   | Returns tensor shape             |
| `.size()`  | Returns tensor size              |
| `.dtype`   | Returns data type                |
| `.device`  | Returns CPU/GPU location         |
| `.ndim`    | Returns number of dimensions     |
| `.numel()` | Returns total number of elements |

---

# Practice

Try this:

```python id="q3a0rt"
x = torch.rand((3, 4, 5))
```

Then run:

```python id="37z6q0"
x.shape
x.size()
x.dtype
x.ndim
x.numel()
x.device
```


### .shape

In [53]:
import torch

In [54]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [55]:
print(x.shape)

torch.Size([2, 3])


3D

In [56]:
x = torch.rand((2,3,224))
x

tensor([[[0.4873, 0.9767, 0.5447,  ..., 0.4498, 0.9230, 0.2971],
         [0.6769, 0.4310, 0.9799,  ..., 0.5988, 0.3311, 0.0800],
         [0.3136, 0.0853, 0.4283,  ..., 0.0144, 0.4097, 0.8507]],

        [[0.9048, 0.0896, 0.3192,  ..., 0.1359, 0.2851, 0.8818],
         [0.6971, 0.3842, 0.4289,  ..., 0.0671, 0.1169, 0.4549],
         [0.3836, 0.9662, 0.0971,  ..., 0.9021, 0.7702, 0.2469]]])

In [57]:
x.shape

torch.Size([2, 3, 224])

### .size()

same as `.shape`

In [58]:
x = torch.rand(2,4)
x

tensor([[0.1401, 0.8316, 0.9542, 0.4639],
        [0.9399, 0.4636, 0.9901, 0.2358]])

In [59]:
x.size()

torch.Size([2, 4])

here we can see single dimension size

In [60]:
x.size(0)

2

In [61]:
x.size(1)

4

### .dtype

to check tensor data type

In [62]:
x = torch.randn(3,4)
x

tensor([[ 0.2488, -0.3219, -0.4684,  0.4105],
        [-0.5525,  1.0187, -0.1317,  0.1786],
        [-1.6865, -0.3630, -0.5298,  1.3282]])

In [63]:
x.dtype

torch.float32

### Type Change

In [64]:
x=x.int()
x

tensor([[ 0,  0,  0,  0],
        [ 0,  1,  0,  0],
        [-1,  0,  0,  1]], dtype=torch.int32)

In [65]:
x.dtype

torch.int32

### .devie

it tells where tensor have?

In [66]:
x = torch.tensor([1,2,3,4])
x

tensor([1, 2, 3, 4])

In [67]:
x.device

device(type='cpu')

In [68]:
device = torch.device("cuda")
device

device(type='cuda')

In [69]:
x = x.to(device)
print(x)
print(x.device)

AssertionError: Torch not compiled with CUDA enabled

In [70]:
import torch
print(torch.cuda.is_available())

False


### .ndim

number of dimension

In [71]:
x = torch.randn(5,4,8)
x

tensor([[[-0.6245, -0.7242,  1.2862, -0.5490, -0.7227, -0.0772, -0.1581,
          -2.6536],
         [-1.2760, -1.1797,  0.1921, -1.5073, -0.7727,  0.5898, -1.3433,
          -0.3979],
         [ 0.5680,  2.2861, -0.7478, -1.7486,  0.2243, -0.2768, -0.8519,
          -0.6107],
         [-1.0010, -1.8453, -0.9227, -0.7857,  0.4868, -0.7563,  1.0328,
           0.8981]],

        [[ 0.4768,  0.5353,  0.2383, -0.6052,  1.4912, -0.6774, -0.9495,
           0.5878],
         [ 0.6156,  0.1364,  1.1224, -1.6508, -1.4015,  0.8857,  0.3484,
          -0.9100],
         [-0.5320,  0.0433, -0.4618,  0.8327, -0.2525, -0.6977, -0.4756,
          -0.6093],
         [-0.0679, -1.3367, -1.7196,  0.1454,  0.7589,  1.1076,  1.0130,
          -0.1861]],

        [[ 1.6435,  0.6194, -1.7238, -0.9971, -1.0882, -2.1388,  1.1292,
           1.5666],
         [ 0.3775, -0.0979,  1.3744, -1.0803,  0.0426, -0.8291,  0.1271,
           0.4286],
         [ 0.1677, -0.6457, -0.4470, -1.8858, -0.0508,  0.4535,  0

In [72]:
x.ndim

3

### .numel()

In [73]:
x.numel()

160